import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    include: ["test/**/*.test.ts"],
    exclude: ["test/integration/**"],
    testTimeout: 10_000,
    pool: "threads",
    coverage: {
      provider: "v8",
      reporter: ["text", "lcov"],
      reportsDirectory: "coverage",
      include: ["src/**/*.ts"],
      exclude: [
        "src/**/*.d.ts",
        // CLI entry — top-level await + try/catch wrapper around main().
        // Its behaviour is fully exercised by test/main.test.ts (subprocess)
        // and test/main.unit.test.ts (in-process); the 6-line glue here
        // is not meaningfully coverable by vitest's v8 instrumentation.
        "src/index.ts",
        // Autogenerated TypeScript wire-contract types. The file is pure
        // `interface` declarations regenerated from the backend message
        // schemas; it compiles to zero runtime code, so v8 instrumentation
        // cannot meaningfully cover it. Drift from the backend schema is
        // caught by the bridge_check tooling, not by unit-test coverage.
        "src/generated/**",
      ],
      thresholds: {
        // Lines stay at 100 — every executable source line is
        // exercised by the suite. The other three metrics sit
        // slightly below 100 because of SDK-defensive `??` arms
        // (the MCP Client guarantees never-undefined values for
        // capabilities + serverInfo, so the in-source fallbacks
        // are unreachable through the real SDK and would require
        // a full Client-class module-mock to exercise) and two
        // anonymous abort-timer arrows in `bridge_fetch.ts` /
        // `ws_token.ts` that fire only after a real 10s fetch
        // hang. Tracked as follow-up work; release-blocker
        // gating is met by lines:100 plus the floors below.
        lines: 100,
        functions: 97,
        statements: 97,
        branches: 92,
      },
    },
  },
});
