import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    include: ["test/**/*.test.ts"],
    exclude: ["test/integration/**"],
    testTimeout: 10_000,
    pool: "threads",
    coverage: {
      provider: "v8",
      reporter: ["text", "lcov"],
      reportsDirectory: "coverage",
      include: ["src/**/*.ts"],
      exclude: [
        "src/**/*.d.ts",
        // CLI entry — top-level await + try/catch wrapper around main().
        // Its behaviour is fully exercised by test/main.test.ts (subprocess)
        // and test/main.unit.test.ts (in-process); the 6-line glue here
        // is not meaningfully coverable by vitest's v8 instrumentation.
        "src/index.ts",
        // Autogenerated TypeScript wire-contract types. The file is pure
        // `interface` declarations regenerated from the backend message
        // schemas; it compiles to zero runtime code, so v8 instrumentation
        // cannot meaningfully cover it. Drift from the backend schema is
        // caught by the bridge_check tooling, not by unit-test coverage.
        "src/generated/**",
      ],
      thresholds: {
        // Floors sit slightly below 100 because of:
        //   - SDK-defensive `??` arms (the MCP Client guarantees
        //     never-undefined values for capabilities + serverInfo,
        //     so the in-source fallbacks are unreachable through
        //     the real SDK and would require a full Client-class
        //     module-mock to exercise);
        //   - two anonymous abort-timer arrows in `bridge_fetch.ts`
        //     / `ws_token.ts` that fire only after a real 10s
        //     fetch hang;
        //   - the rejection arm of the runner's terminal
        //     `runForever().then(success, failure)` chain in
        //     `ws_client.ts` — `runForever()` is now guaranteed to
        //     resolve cleanly because every reconnect-loop error
        //     is caught + logged inside the loop body, but the
        //     rejection handler stays as a defensive bridge
        //     against future-introduced throw paths.
        // Tracked as follow-up work; release-blocker gating is
        // met by the floors below.
        lines: 99,
        functions: 96,
        statements: 97,
        branches: 91,
      },
    },
  },
});
