/**
 * Bridge-specific type aliases, unions, and helpers.
 *
 * Wire-contract types are autogenerated from Snapper backend message
 * schemas; see `./generated/wire-contract.js`. This file adds the
 * bridge's narrower unions, friendlier alias names, and helper
 * functions on top of those raw types.
 *
 * The `default:` arm of any switch on `frame.type` MUST drop unknown
 * server-emitted types silently so the bridge stays forward-compatible
 * when the backend ships new frame variants ahead of the npm bridge
 * update.
 */

import type {
  AiReviewCapsViolationFrameData,
  AiReviewDecisionAckFrameData,
  AiReviewRequestFrameData,
  FrameEnvelope,
  OrderEventData,
  SignalData,
  WSAuthCompleteResponse,
  WSAuthExpiredResponse,
  WSAuthFailedResponse,
  WSAuthOkResponse,
  WSAuthRequiredResponse,
  WSAuthenticateRequest,
  WSErrorResponse,
  WSPingRequest,
  WSPongResponse,
  WSReauthOkResponse,
  WSReauthRequest,
  WSReauthRequiredResponse,
  WSSubscribeRequest,
  WSSubscriptionSuccessResponse,
} from "./generated/wire-contract.js";

export type { FrameEnvelope } from "./generated/wire-contract.js";

/* --------------------------------------------------------------------
 * Bridge-friendly aliases for the server-emitted control frames
 * ------------------------------------------------------------------ */

export type AuthRequiredFrame = WSAuthRequiredResponse;
export type AuthOkFrame = WSAuthOkResponse;
export type AuthCompleteFrame = WSAuthCompleteResponse;
export type AuthFailedFrame = WSAuthFailedResponse;
export type ReauthRequiredFrame = WSReauthRequiredResponse;
export type ReauthOkFrame = WSReauthOkResponse;
export type AuthExpiredFrame = WSAuthExpiredResponse;
export type SubscriptionSuccessFrame = WSSubscriptionSuccessResponse;
export type PongFrame = WSPongResponse;
export type ErrorFrame = WSErrorResponse;

export type ControlFrame =
  | AuthRequiredFrame
  | AuthOkFrame
  | AuthCompleteFrame
  | AuthFailedFrame
  | ReauthRequiredFrame
  | ReauthOkFrame
  | AuthExpiredFrame
  | SubscriptionSuccessFrame
  | PongFrame
  | ErrorFrame;

export type ControlFrameType = ControlFrame["type"];

/* --------------------------------------------------------------------
 * Bridge-friendly aliases for the server-emitted data frames
 * ------------------------------------------------------------------ */

export type AiReviewRequestFrame = AiReviewRequestFrameData;
export type AiReviewDecisionAckFrame = AiReviewDecisionAckFrameData;
export type AiReviewCapsViolationFrame = AiReviewCapsViolationFrameData;
export type SignalFrame = SignalData;
export type OrderEventFrame = OrderEventData;

export type AiReviewFrame =
  | AiReviewRequestFrame
  | AiReviewDecisionAckFrame
  | AiReviewCapsViolationFrame;

export type GenericDataFrame = SignalFrame | OrderEventFrame;

/**
 * Closed union of every server-emitted frame the bridge currently
 * understands. The `default:` arm of any switch on `frame.type` MUST
 * drop unknown types silently rather than throw — the bridge stays
 * forward-compatible with backend deployments that ship new frame
 * variants ahead of the npm bridge update.
 */
export type ServerFrame = ControlFrame | AiReviewFrame | GenericDataFrame;

/**
 * Closed union of server-emitted frames the publisher actually
 * stamps a topic on. Distinct from the broader `ServerFrame` (which
 * also includes control frames whose `topic` is always null on the
 * wire). Use the `hasTopic` runtime guard to safely narrow a
 * `ServerDataFrame` to `PublishedDataFrame` before reading
 * `frame.topic` as a routing key.
 */
export type ServerDataFrame =
  | AiReviewRequestFrame
  | AiReviewDecisionAckFrame
  | AiReviewCapsViolationFrame
  | SignalFrame
  | OrderEventFrame;

/**
 * Narrowed alias asserting `topic` is non-null. Produced from a
 * `ServerDataFrame` via the `hasTopic` runtime guard; the type
 * system alone cannot prove non-null because every frame's
 * envelope declares `topic: string | null`.
 */
export type PublishedDataFrame = ServerDataFrame & { readonly topic: string };

/**
 * Runtime narrowing guard for the topic field. Consumers MUST call
 * this before using `frame.topic` as a routing key. Returns true
 * when the publisher has stamped a topic onto the frame; false on
 * control frames + any data frame still in producer-construction
 * state where topic has not been populated yet.
 */
export function hasTopic<F extends FrameEnvelope>(
  frame: F,
): frame is F & { readonly topic: string } {
  return typeof frame.topic === "string";
}

/* --------------------------------------------------------------------
 * Bridge-friendly aliases for the client-emitted frames the watch
 * subcommand sends
 * ------------------------------------------------------------------ */

export type AuthenticateRequestFrame = WSAuthenticateRequest;
export type ReauthRequestFrame = WSReauthRequest;
export type SubscribeRequestFrame = WSSubscribeRequest;
export type PingRequestFrame = WSPingRequest;

/**
 * Closed union of client-emitted frames the watch subcommand sends.
 * Other client frame types (unsubscribe, get_subscriptions) are not
 * needed for the watch flow and are deliberately omitted to keep the
 * surface narrow.
 */
export type WatchClientFrame =
  | AuthenticateRequestFrame
  | ReauthRequestFrame
  | SubscribeRequestFrame
  | PingRequestFrame;

/* --------------------------------------------------------------------
 * Dedup helpers
 * ------------------------------------------------------------------ */

/**
 * AI-review dedup triple. The bridge keeps an LRU cache keyed on
 * this triple to drop server-side replays after reconnects.
 * `dispatch_version` is the primary discriminator; `type` and
 * `review_public_id` exist to disambiguate frames that share a
 * review across the three AI-review variants.
 */
export interface DedupKey {
  readonly type: string;
  readonly review_public_id: string;
  readonly dispatch_version: number;
}

/**
 * Helper: extract the dedup triple from any AI-review frame.
 * Non-AI frames return ``null`` — they don't participate in the
 * dedup contract.
 */
export function dedupKeyOf(frame: ServerFrame): DedupKey | null {
  if (
    frame.type === "ai_review.request" ||
    frame.type === "ai_review.decision_ack" ||
    frame.type === "ai_review.caps_violation"
  ) {
    return {
      type: frame.type,
      review_public_id: frame.review_public_id,
      dispatch_version: frame.dispatch_version,
    };
  }
  return null;
}
